apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: testapp1
  replicas: {{ .Values.testapp1.container.num }}
  template:
    metadata:
      labels:
        app: testapp1
    spec:
      containers:
        - name: testapp1
          imagePullPolicy: IfNotPresent
          image: docker.io/library/test-app1:20240630-1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: {{ .Values.testapp1.container.port }}
          env:
            - name: PORT
              value: !string {{ .Values.testapp1.container.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: testapp1-service
  labels:
    app: testapp1
spec:
  type: NodePort
  ports:
    - port: {{ .Values.testapp1.container.port }}
      targetPort: {{ .Values.testapp1.container.port }}
      nodePort: {{ .Values.testapp1.container.nodeport }}
      protocol: TCP
  selector:
    app: testapp1
